name: flutter_alarm_app
description: A Flutter application for setting alarms with aggressive wake-up sounds.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  flutter_local_notifications: 18.0.1
  audio_service: ^0.18.0
  just_audio: ^0.9.0
  flutter_bloc: ^8.0.0
  timezone: ^0.9.2
  audio_session: ^0.1.18
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/alarm_sounds/
    - assets/audio/voices/
    - assets/animations/
    - assets/fonts/